//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance4You.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string AppUserID { get; set; }
        public string RegNumber { get; set; }
        public System.DateTime DOM { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Engine { get; set; }
    }
}
