//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance4You.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int Id { get; set; }
        public string AppUserID { get; set; }
        public string Phone { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public string County { get; set; }
        public bool AddDriver { get; set; }
    }
}
