//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance4You.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingHistory
    {
        public int Id { get; set; }
        public string AppUserId { get; set; }
        public string LicenceNo { get; set; }
        public int ClaimsDiscount { get; set; }
        public int PenlatyPoints { get; set; }
        public string ConvictionType { get; set; }
        public Nullable<System.DateTime> ConvictionDate { get; set; }
        public string AccidentType { get; set; }
        public Nullable<System.DateTime> AccidentDate { get; set; }
    }
}
