//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance4You.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string SiteUserId { get; set; }
        public Nullable<int> PolicyId { get; set; }
    
        public virtual Policy Policy { get; set; }
    }
}
