//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance4You.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrivingHistory()
        {
            this.Drivers = new HashSet<Driver>();
        }
    
        public int Id { get; set; }
        public int LicenceNo { get; set; }
        public int ClaimsDiscount { get; set; }
        public int PenlatyPoints { get; set; }
        public string ConvictionType { get; set; }
        public Nullable<System.DateTime> ConvictionDate { get; set; }
        public string AccidentType { get; set; }
        public Nullable<System.DateTime> AccidentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
