//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance4You.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int Id { get; set; }
        public int CarID { get; set; }
        public int DriverID { get; set; }
        public Nullable<int> AdditionalDriverID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public int QuoteID { get; set; }
        public bool Checked { get; set; }
        public Nullable<bool> Rejected { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
